# Generated by Django 4.2.5 on 2023-09-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='heroes',
            fields=[
                ('nivel', models.CharField(max_length=1000, primary_key=True, serialize=False)),
            ],
        ),
    ]
