# Generated by Django 4.2.5 on 2023-09-26 20:26

import clash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='heroes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clash.models.img),
        ),
    ]
