# Generated by Django 4.2.5 on 2023-10-01 17:30

import clash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0002_heroes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Heroina',
            fields=[
                ('nivel', models.IntegerField(db_column='Nivel', primary_key=True, serialize=False)),
                ('damage', models.IntegerField(blank=True, db_column='Damage', null=True)),
                ('hit', models.FloatField(blank=True, db_column='Hit', null=True)),
                ('hp', models.FloatField(blank=True, db_column='HP', null=True)),
                ('upcost', models.IntegerField(blank=True, db_column='UPcost', null=True)),
                ('uptime', models.TextField(blank=True, db_column='UPTime', null=True)),
                ('th', models.IntegerField(blank=True, db_column='TH', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clash.models.img)),
            ],
            options={
                'db_table': 'Heroina',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='King',
            fields=[
                ('nivel', models.IntegerField(db_column='Nivel', primary_key=True, serialize=False)),
                ('damage', models.IntegerField(blank=True, db_column='Damage', null=True)),
                ('hit', models.FloatField(blank=True, db_column='Hit', null=True)),
                ('hp', models.FloatField(blank=True, db_column='HP', null=True)),
                ('upcost', models.IntegerField(blank=True, db_column='UPcost', null=True)),
                ('uptime', models.TextField(blank=True, db_column='UPTime', null=True)),
                ('th', models.IntegerField(blank=True, db_column='TH', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clash.models.img)),
            ],
            options={
                'db_table': 'King',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Quenn',
            fields=[
                ('nivel', models.IntegerField(db_column='Nivel', primary_key=True, serialize=False)),
                ('damage', models.IntegerField(blank=True, db_column='Damage', null=True)),
                ('hit', models.FloatField(blank=True, db_column='Hit', null=True)),
                ('hp', models.FloatField(blank=True, db_column='HP', null=True)),
                ('upcost', models.IntegerField(blank=True, db_column='UPcost', null=True)),
                ('uptime', models.TextField(blank=True, db_column='UPTime', null=True)),
                ('th', models.IntegerField(blank=True, db_column='TH', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clash.models.img)),
            ],
            options={
                'db_table': 'Quenn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Warden',
            fields=[
                ('nivel', models.IntegerField(db_column='Nivel', primary_key=True, serialize=False)),
                ('damage', models.IntegerField(blank=True, db_column='Damage', null=True)),
                ('hit', models.FloatField(blank=True, db_column='Hit', null=True)),
                ('hp', models.FloatField(blank=True, db_column='HP', null=True)),
                ('aura', models.CharField(blank=True, db_column='AURA', max_length=100, null=True)),
                ('upcost', models.IntegerField(blank=True, db_column='UPcost', null=True)),
                ('uptime', models.TextField(blank=True, db_column='UPTime', null=True)),
                ('th', models.IntegerField(blank=True, db_column='TH', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=clash.models.img)),
            ],
            options={
                'db_table': 'Warden',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='heroes',
        ),
    ]
