# Generated by Django 4.2.5 on 2023-10-01 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0003_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroina',
            options={},
        ),
        migrations.AlterModelOptions(
            name='king',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quenn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='warden',
            options={},
        ),
    ]
