# Generated by Django 4.2.5 on 2023-10-01 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clash', '0004_alter_heroina_options_alter_king_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroina',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='king',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='quenn',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='warden',
            options={'managed': False},
        ),
    ]
